-- InvestAgent relational schema.
--
-- Self-contained and idempotent: every object is CREATE ... IF NOT EXISTS, so
-- re-running is a no-op rather than an error. There are no down-migrations —
-- the trade for keeping Terraform, its state backend and Alembic out of the
-- path is that undoing something is a new numbered file.
--
-- Runs against the application database, so no \connect is needed here (unlike
-- grant-uai-access.sql, which has to visit `postgres` for pgaadauth).
--
-- Three conventions worth stating once rather than per column:
--
--   * Money is NUMERIC(18,4), never float. Binary floating point cannot
--     represent a penny exactly and the whole experiment is a P&L figure.
--   * Quantities are NUMERIC(18,6): Alpaca fills fractional shares, so a £20
--     approved trade on a $180 stock is not a whole number of shares.
--   * Every timestamp is timestamptz. The cron schedules are UTC and British
--     Summer Time shifts the wall clock under them, so a naive timestamp would
--     silently mean two different instants across the year.
--
-- Statuses and actions are `text` + CHECK rather than enum types deliberately:
-- CREATE TYPE has no IF NOT EXISTS, and adding a value to an enum later is a
-- migration that cannot run inside a transaction. A CHECK constraint is
-- droppable and re-addable.

-- Records which files in sql/ have been applied. Each numbered file inserts its
-- own row at the end, keeping the runner script ignorant of what it runs.
CREATE TABLE IF NOT EXISTS schema_migrations (
  filename   text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Reference data: the watchlist and the market data fetched for it
-- ---------------------------------------------------------------------------

-- The ticker is the natural key throughout, so it is the primary key rather
-- than a surrogate id: it keeps every fact table readable in a raw psql session
-- without a join.
CREATE TABLE IF NOT EXISTS companies (
  ticker    text PRIMARY KEY,
  name      text NOT NULL,
  exchange  text,
  sector    text,
  currency  text NOT NULL DEFAULT 'USD',
  -- Dropping a ticker from the watchlist must not orphan its prices, news or
  -- decisions, so retirement is a flag rather than a DELETE.
  is_active boolean NOT NULL DEFAULT true,
  added_at  timestamptz NOT NULL DEFAULT now()
);

-- Daily bars. The composite primary key is what makes the fetch idempotent:
-- re-running the agent on the same day upserts rather than duplicating.
CREATE TABLE IF NOT EXISTS prices (
  ticker     text NOT NULL REFERENCES companies (ticker),
  bar_date   date NOT NULL,
  open_usd   numeric(18, 4),
  high_usd   numeric(18, 4),
  low_usd    numeric(18, 4),
  close_usd  numeric(18, 4) NOT NULL,
  volume     bigint,
  source     text NOT NULL DEFAULT 'alpaca',
  fetched_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (ticker, bar_date)
);

CREATE INDEX IF NOT EXISTS prices_bar_date_idx ON prices (bar_date DESC);

-- ---------------------------------------------------------------------------
-- News and its analysis
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS news (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- The provider's own article id. UNIQUE is the deduplication mechanism: the
  -- news endpoint returns overlapping windows on consecutive runs, and paying
  -- an LLM twice to read the same article is the cost that matters here.
  external_id  text NOT NULL UNIQUE,
  source       text NOT NULL DEFAULT 'alpaca',
  -- An article routinely mentions several watchlist names, so the relationship
  -- is an array with a GIN index rather than a join table: it is only ever
  -- queried as "news mentioning X", never the reverse.
  tickers      text[] NOT NULL DEFAULT '{}',
  headline     text NOT NULL,
  summary      text,
  author       text,
  url          text,
  published_at timestamptz NOT NULL,
  fetched_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS news_published_at_idx ON news (published_at DESC);
CREATE INDEX IF NOT EXISTS news_tickers_idx ON news USING gin (tickers);

-- Output of the cheap relevance filter (Haiku), one row per article/ticker pair
-- it was asked about.
CREATE TABLE IF NOT EXISTS news_analysis (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  news_id         bigint NOT NULL REFERENCES news (id) ON DELETE CASCADE,
  ticker          text NOT NULL,
  relevant        boolean NOT NULL,
  sentiment       text CHECK (sentiment IN ('positive', 'neutral', 'negative')),
  -- -1.0000 to 1.0000.
  sentiment_score numeric(6, 4) CHECK (sentiment_score BETWEEN -1 AND 1),
  rationale       text,
  model           text NOT NULL,
  prompt_version  text NOT NULL,
  input_tokens    integer,
  output_tokens   integer,
  analysed_at     timestamptz NOT NULL DEFAULT now(),
  -- Model and prompt version are part of the key so re-analysing a back
  -- catalogue after a prompt change adds rows rather than destroying the
  -- record of what the previous prompt concluded.
  UNIQUE (news_id, ticker, model, prompt_version)
);

CREATE INDEX IF NOT EXISTS news_analysis_ticker_relevant_idx
  ON news_analysis (ticker, relevant);

-- ---------------------------------------------------------------------------
-- The portfolio. These tables are the source of truth for what is held;
-- Alpaca is the executor and the data feed, not the ledger.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS portfolio (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text NOT NULL UNIQUE,
  base_currency     text NOT NULL DEFAULT 'GBP',
  -- The notional £500 the experiment starts with, kept separately from the
  -- running cash balance so total return stays computable after any number of
  -- trades.
  initial_cash_gbp  numeric(18, 4) NOT NULL,
  cash_gbp          numeric(18, 4) NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS positions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portfolio_id  bigint NOT NULL REFERENCES portfolio (id) ON DELETE CASCADE,
  ticker        text NOT NULL REFERENCES companies (ticker),
  quantity      numeric(18, 6) NOT NULL,
  -- Held in both currencies rather than derived on read: the GBP cost basis
  -- depends on the rate at the time of each fill, which no later rate recovers.
  avg_cost_usd  numeric(18, 4) NOT NULL,
  avg_cost_gbp  numeric(18, 4) NOT NULL,
  opened_at     timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (portfolio_id, ticker)
);

-- ---------------------------------------------------------------------------
-- The audit trail: what the agent did, what the AI said, what the risk engine
-- allowed, and what was actually executed.
-- ---------------------------------------------------------------------------

-- One row per agent job execution, opened at the start and closed at the end,
-- so a crashed run leaves evidence rather than nothing.
CREATE TABLE IF NOT EXISTS agent_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at         timestamptz NOT NULL DEFAULT now(),
  finished_at        timestamptz,
  status             text NOT NULL DEFAULT 'running'
                       CHECK (status IN ('running', 'succeeded', 'failed')),
  trigger            text NOT NULL DEFAULT 'schedule'
                       CHECK (trigger IN ('schedule', 'manual')),
  dry_run            boolean NOT NULL DEFAULT false,
  -- The image tag is the immutable git sha the Makefile builds with, which is
  -- what makes a run reproducible.
  image_tag          text,
  tickers_considered integer,
  news_fetched       integer,
  news_relevant      integer,
  decisions_made     integer,
  trades_executed    integer,
  input_tokens       integer,
  output_tokens      integer,
  -- Six decimal places because a single cheap filter call costs fractions of a
  -- cent and the point of tracking it is to catch a run that suddenly doesn't.
  cost_usd           numeric(18, 6),
  error              text
);

CREATE INDEX IF NOT EXISTS agent_runs_started_at_idx ON agent_runs (started_at DESC);

-- The audit-critical table. It carries enough to replay any decision against
-- exactly what the AI saw and what the risk engine then did to it.
CREATE TABLE IF NOT EXISTS ai_decisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id                 bigint REFERENCES agent_runs (id) ON DELETE SET NULL,
  decided_at             timestamptz NOT NULL DEFAULT now(),
  ticker                 text NOT NULL REFERENCES companies (ticker),
  action                 text NOT NULL CHECK (action IN ('BUY', 'SELL', 'HOLD')),
  -- 0.0000 to 1.0000; the risk engine has a confidence floor.
  confidence             numeric(5, 4) CHECK (confidence BETWEEN 0 AND 1),
  reasoning              text,
  risks                  text,
  model                  text NOT NULL,
  prompt_version         text NOT NULL,
  -- The articles fed to this decision. No foreign key is possible from an
  -- array, which is accepted: news rows are never deleted.
  news_ids               bigint[] NOT NULL DEFAULT '{}',
  recommended_amount_gbp numeric(18, 4),
  -- What the risk engine permitted. NULL for HOLD, 0 where the engine refused
  -- outright — different facts, so not collapsed into one.
  approved_amount_gbp    numeric(18, 4),
  -- The portfolio as the model was shown it, and the engine's full verdict
  -- including every reason applied and the single binding constraint. jsonb
  -- rather than columns because both shapes will change with the code, and a
  -- historical row must keep the shape it was written with.
  portfolio_state        jsonb,
  risk_verdict           jsonb,
  input_tokens           integer,
  output_tokens          integer
);

CREATE INDEX IF NOT EXISTS ai_decisions_decided_at_idx ON ai_decisions (decided_at DESC);
CREATE INDEX IF NOT EXISTS ai_decisions_ticker_idx ON ai_decisions (ticker, decided_at DESC);
CREATE INDEX IF NOT EXISTS ai_decisions_run_id_idx ON ai_decisions (run_id);

CREATE TABLE IF NOT EXISTS trades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portfolio_id    bigint NOT NULL REFERENCES portfolio (id) ON DELETE CASCADE,
  -- Nullable so a trade placed by hand is still recordable.
  decision_id     bigint REFERENCES ai_decisions (id) ON DELETE SET NULL,
  ticker          text NOT NULL REFERENCES companies (ticker),
  side            text NOT NULL CHECK (side IN ('BUY', 'SELL')),
  quantity        numeric(18, 6) NOT NULL,
  price_usd       numeric(18, 4),
  notional_usd    numeric(18, 4),
  notional_gbp    numeric(18, 4),
  -- Stored per trade, not looked up later: the £500 figure has to stay
  -- reconstructible from the row itself.
  fx_rate_gbp_usd numeric(18, 6) NOT NULL,
  broker          text NOT NULL DEFAULT 'alpaca',
  -- Absent while DRY_RUN is on, and absent for a rejected order.
  broker_order_id text UNIQUE,
  status          text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'submitted', 'filled',
                                      'partially_filled', 'cancelled',
                                      'rejected', 'simulated')),
  -- A dry run persists the whole decision path without submitting an order, so
  -- the flag is what keeps simulated rows out of the real P&L.
  dry_run         boolean NOT NULL DEFAULT false,
  submitted_at    timestamptz,
  filled_at       timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS trades_created_at_idx ON trades (created_at DESC);
CREATE INDEX IF NOT EXISTS trades_ticker_idx ON trades (ticker, created_at DESC);

-- ---------------------------------------------------------------------------
-- Daily rollups, written by the summary job
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS daily_performance (
  portfolio_id        bigint NOT NULL REFERENCES portfolio (id) ON DELETE CASCADE,
  as_of               date NOT NULL,
  cash_gbp            numeric(18, 4) NOT NULL,
  positions_value_gbp numeric(18, 4) NOT NULL,
  total_value_gbp     numeric(18, 4) NOT NULL,
  pnl_gbp             numeric(18, 4) NOT NULL,
  -- Percent, not a fraction: 12.3400 means +12.34%.
  pnl_pct             numeric(10, 4) NOT NULL,
  fx_rate_gbp_usd     numeric(18, 6) NOT NULL,
  computed_at         timestamptz NOT NULL DEFAULT now(),
  -- Re-running the summary for a day overwrites its row rather than adding a
  -- second one.
  PRIMARY KEY (portfolio_id, as_of)
);

-- The comparison series: what the same notional would be worth in each
-- benchmark. Alpaca only covers US-listed instruments, so these are honest
-- proxies (EWU for the UK, not the FTSE 100) and the UI labels them as such —
-- the label lives in application config, not here, because it describes the
-- symbol rather than the day.
CREATE TABLE IF NOT EXISTS benchmarks (
  symbol          text NOT NULL,
  as_of           date NOT NULL,
  -- Nullable: the 5% savings-account benchmark is computed arithmetically and
  -- has no market price.
  close_usd       numeric(18, 4),
  fx_rate_gbp_usd numeric(18, 6),
  value_gbp       numeric(18, 4) NOT NULL,
  source          text,
  fetched_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (symbol, as_of)
);

CREATE INDEX IF NOT EXISTS benchmarks_as_of_idx ON benchmarks (as_of DESC);

-- The rendered daily email, kept so the dashboard can show the same body that
-- was sent rather than re-generating it.
CREATE TABLE IF NOT EXISTS daily_summaries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  as_of             date NOT NULL UNIQUE,
  subject           text NOT NULL,
  body_markdown     text,
  body_html         text,
  model             text,
  prompt_version    text,
  email_status      text NOT NULL DEFAULT 'pending'
                      CHECK (email_status IN ('pending', 'sent', 'failed', 'skipped')),
  email_provider_id text,
  email_error       text,
  sent_at           timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------

INSERT INTO schema_migrations (filename) VALUES ('001-schema.sql')
ON CONFLICT (filename) DO NOTHING;

\echo '==> tables:'
SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;
