-- The weekly review: how the experiment is doing, and what to change.
--
-- The daily summary answers "what happened today". This answers a question a
-- single day cannot: is the agent actually working, and which knob is the one
-- worth turning? The review job reads a week of the tables the agent and the
-- summary already wrote, hands the model those figures, and stores what it
-- says.
--
-- Idempotent like every file here, and `CREATE ... IF NOT EXISTS` throughout.

CREATE TABLE IF NOT EXISTS weekly_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- The window reviewed, inclusive at both ends. Stored rather than derived
  -- from `period_end` and a constant: the length is a code decision today and
  -- a row has to keep saying what it actually covered if that ever changes.
  period_start      date NOT NULL,
  -- Unique, so re-running a week overwrites its review rather than adding a
  -- second one — the same property `daily_summaries.as_of` has.
  period_end        date NOT NULL UNIQUE,
  subject           text NOT NULL,
  -- The model's prose on its own, separate from the rendered email body below.
  -- The dashboard renders this as text: `body_html` is Markdown-rendered model
  -- output, and Python-Markdown passes raw HTML through, so putting that in the
  -- DOM would let a model's output inject markup. The dashboard also already
  -- shows the figures as live tables, so it wants the commentary and not the
  -- email's copy of them.
  assessment        text,
  body_markdown     text,
  body_html         text,
  -- The deterministic figures the model was shown, exactly as it was shown
  -- them. Kept because the review's argument is only readable months later
  -- against the numbers behind it, and because the prompt will change.
  -- Decimals are serialised as strings, as they are in ai_decisions.
  metrics           jsonb,
  -- The model's proposed changes, structured rather than buried in the prose.
  -- This is the column with a second use: "has it asked for the same change
  -- three weeks running?" is a query against this, and a proposal that keeps
  -- reappearing is a much stronger signal than one that appeared once.
  --
  -- Advisory only. Nothing in this system reads these back and applies them —
  -- a risk limit changes when a human edits risklimits.py, which is the whole
  -- point of the limits being deterministic and outside the model's reach.
  recommendations   jsonb,
  model             text,
  prompt_version    text,
  email_status      text NOT NULL DEFAULT 'pending'
                      CHECK (email_status IN ('pending', 'sent', 'failed', 'skipped')),
  email_provider_id text,
  email_error       text,
  sent_at           timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT weekly_reviews_period CHECK (period_start <= period_end)
);

CREATE INDEX IF NOT EXISTS weekly_reviews_period_end_idx ON weekly_reviews (period_end DESC);

INSERT INTO schema_migrations (filename) VALUES ('005-weekly-reviews.sql')
ON CONFLICT (filename) DO NOTHING;

\echo '==> weekly_reviews columns:'
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'weekly_reviews'
ORDER BY ordinal_position;
